### ISSUE TITLE
[1.19] Client-side crash while attempting to mine the ore

### ISSUE THREAD

**Issue by NyakoFox** [MehVahdJukaar/Randomium#10]
This is on a dedicated server. It seems that attempting to mine the ore will crash due to a random int call in getRandomSound. A crash log is [here](https://0x0.st/o1-U.txt).

**Comment by NyakoFox** [comment]
Looks like Randomium.SOUNDS gets added to on the server, so when the client tries to use it, it's empty.

**Comment by MehVahdJukaar** [comment]
should be fixed
