### ISSUE TITLE
all Randomium ores only drops luck potions

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [MehVahdJukaar/Randomium#13]
Minecraft version: 1.19.4
Forge Version: 45.0.41
Randomium version: 1.19.4-1.20

Title says all. I've mined a total of 8 randomium so far in my world and have only gotten luck potions. Tested in a creative world and had the same issue. I didnt look super close into it, but I assume items from tabs arent actually being added to the loot list (done here: https://github.com/MehVahdJukaar/Randomium/blob/1.20/common/src/main/java/net/mehvahdjukaar/randomium/Randomium.java#L105-L124)

**Comment by MehVahdJukaar** [comment]
I think tabs are initialised later now so that code runs too early. I'll have to rethink that

**Comment by GizmoTheMoonPig** [comment]
updated the mod to 1.22 and im still having this problem. Looks like the code still runs early only on forge, and because the list is never actually empty (which it checks for [here](https://github.com/MehVahdJukaar/Randomium/blob/1.20/common/src/main/java/net/mehvahdjukaar/randomium/Randomium.java#L137)) the loot still only contains luck potions

**Comment by GizmoTheMoonPig** [comment]
updated the mod to 1.23 (I did this a while ago, btu forgot to report), and well, now the ores drop nothing at all. No luck potions or anything.

**Comment by GizmoTheMoonPig** [comment]
I finally got around to actually investigating the issue. Apparently tabs dont even initialize until you open the creative inventory, so theyll NEVER even exist in survival mode. 1.20 should hopefully change this since tabs are gonna become a proper registry in that version

**Comment by MehVahdJukaar** [comment]
Oh darn what the hell
