### ISSUE TITLE
randomium drops nothing

### ISSUE THREAD

**Issue by Xplodin** [MehVahdJukaar/Randomium#19]
I have a custom pack I threw together so idk if its a mod conflict but it drops either air or nothing.
1.20 btw

this is the only thing to come up in debug.log
[Server thread/DEBUG] [Dynamic Player Progression and Player Difficulty/]: [Block Damage PICKAXE] ServerPlayer['BobTheWizard7'/1329, l='ServerLevel[Beantopia]', x=-251.21, y=46.00, z=108.70] destroyed Block{randomium:randomium_ore}[lit=false] with emerald_pickaxe

**Comment by Xplodin** [comment]
also just got this in console when breaking it 
https://gist.github.com/Xplodin/afa7646dd0b44ed00966270de6bdb3c3

**Comment by MehVahdJukaar** [comment]
Seems like a big part of the mod just isn't possible with new creative tabs stuff. That's bad

**Comment by Xplodin** [comment]
after updating the mod I now get this crash along with something with rats
https://gist.github.com/Xplodin/4721e88672ef5dd98af0e55b52fe9f29

**Comment by MehVahdJukaar** [comment]
Issue with Rats mod. Nothing i can do here beside opening an issue on their page
