### ISSUE TITLE
Won't launch serverside

### ISSUE THREAD

**Issue by thiccmeme** [MehVahdJukaar/Randomium#2]
[crash-2021-09-14_22.26.56-fml.txt](https://github.com/MehVahdJukaar/Randomium/files/7166292/crash-2021-09-14_22.26.56-fml.txt)

attached is a crash report from my forge server, it's running mohist but the issue was with a client class being unable to load and as such, I doubt it is the version of the server that is the issue. 

its running 1.16.5 forge version 36.2.4 and version 1.2 of randomium 

please let me know if there is anymore information I can provide as I'd really like to help solve this issue so I can use the mod on my server for me and my friends :)

**Comment by MehVahdJukaar** [comment]
fixed in 1.3
