### ISSUE TITLE
[Question] Is is possible to change the ore generation rate?

### ISSUE THREAD

**Issue by ArsiTheFox** [MehVahdJukaar/Randomium#26]
Question asks it all xP

**Comment by MehVahdJukaar** [comment]
Yes, like all wprldgen can be changed with datapack

**Comment by ArsiTheFox** [comment]
This may need to be also be changeable in the config too like a setting called "generationAttemptsPerChunk=[DECIMAL #]"

**Comment by MehVahdJukaar** [comment]
Is that a question? No it can be tweaked with datapakc. Adding a config would be non trivial and redundant

**Comment by ArsiTheFox** [comment]
Some people don't know how to make a custom datapack for their game. But thank you for replying and I am sorry

**Comment by MehVahdJukaar** [comment]
You can read about that in the supplementaries wiki or official Minecraft wiki
