### ISSUE TITLE
Clients Unable to Join Dedicated Server with Apotheosis

### ISSUE THREAD

**Issue by BookerCatch** [MehVahdJukaar/Randomium#27]
With Randomium, Apotheosis, and both mods' dependencies loaded, the client is unable to join a dedicated server. Client will get stuck on the login screen unable to join, and then the launcher will freeze as the logs get spammed indefinitely. Please see debug and latest logs attached below. Unsure which of the two is the culprit, but I thought it prudent to bring it to your attention. 

[debug.log](https://github.com/MehVahdJukaar/Randomium/files/13753850/debug.log)
[latest.log](https://github.com/MehVahdJukaar/Randomium/files/13753851/latest.log)

**Comment by MehVahdJukaar** [comment]
issue comes directly from that mod. its their issue
