### ISSUE TITLE
[Fabric, 1.20.1] No correct tool

### ISSUE THREAD

**Issue by Lifeline684** [MehVahdJukaar/Randomium#32]
No matter what tool I use, it is always wrong when trying to mine randomium ore. It will not ever drop anything and takes ages to mine no matter what tool I use.

**Comment by MehVahdJukaar** [comment]
Sounds like you have a mod that's breaking the mineable tag for all stone blocks

**Comment by Lifeline684** [comment]
It appears so. well shit. Sorry for wasting your time lol. off to go figure that out ig lmao
