### ISSUE TITLE
Crash on joining world

### ISSUE THREAD

**Issue by oldmooshie** [MehVahdJukaar/Randomium#36]
I tried a binary search and found that this mod is the culprit of the attached crash, but I don't know enough to figure out why.

[crash-2024-09-03_16.50.46-server.txt](https://github.com/user-attachments/files/16856013/crash-2024-09-03_16.50.46-server.txt)

**Comment by MehVahdJukaar** [comment]
issue is from this mod

	at net.povstalec.sgjourney.common.blocks.SymbolBlock.m_5871_(SymbolBlock.java:151) ~[Stargate%20Journey-1.20.1-0.6.27.jar%23639!/:0.6.27] {re:classloading}

**Comment by oldmooshie** [comment]
Deleting this mod (simply disabling it didn't help) seems to have solved the problem. Thanks!
