### ISSUE TITLE
Removed spawns config from 1.18.2 to 1.20.1

### ISSUE THREAD

**Issue by Magminer54** [MehVahdJukaar/Randomium#37]
Why was this removed and is there any way to fix it?
![grafik](https://github.com/user-attachments/assets/7c037fae-72a8-4b3c-82dc-3a807a8fab68)
![grafik](https://github.com/user-attachments/assets/e34f3bcd-95fe-4855-9834-0830d0026509)

**Comment by MehVahdJukaar** [comment]
that's because  from 1.18 all worldgen stuff is data driven. you can tweak worldgen from any mod with datapack

**Comment by Magminer54** [comment]
> that's because from 1.18 all worldgen stuff is data driven. you can tweak worldgen from any mod with datapack

could you maybe link some sort of help to this like an article about that because i tried to find an explanation but nothing came up really
