### ISSUE TITLE
Recipe conflict with KubeJS replaceInput function (1.16.5)

### ISSUE THREAD

**Issue by MrZora** [MehVahdJukaar/Randomium#7]
`[02:55:49] [ERR  ] Error occurred while handling event 'recipes': Wrapped java.lang.ArithmeticException (server_scripts:atlas_compat.js#58)`
`[02:55:49] [ERR  ] Error occurred while handling event 'recipes': Wrapped java.lang.ArithmeticException (server_scripts:atlas.js#577)`
There appears to be a conflict with the randomium:duplicate recipe and KubeJS's replaceInput function. An ArithmeticException error points to the first replaceInput event in any given script at launch, with multiple individual instances if there are several scripts.

**Comment by MrZora** [comment]
Sorry for the late reply!
I was using KubeJS to load a variety of recipe changes in a personal modpack and encountered this issue when running compatibility scripts to unify mod metal inputs. The above errors went away when Randomium was disabled, and I am unsure of the reasons why.

**Comment by MehVahdJukaar** [comment]
That's weird. Are you specifically trying to change the randomium recipe? I'm not doing anything special with that one report this to kube js since it is a problem with that mod
